# Generated by Django 5.2.7 on 2025-10-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('km_track_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='identifier',
            field=models.CharField(default='---', max_length=100),
        ),
        migrations.CreateModel(
            name='TelemetryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('odometer', models.FloatField()),
                ('distance', models.FloatField()),
                ('duration', models.DurationField()),
                ('idle_time', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='km_track_api.vehicle')),
            ],
        ),
    ]
