# Generated by Django 5.2.7 on 2025-11-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veiculo_id', models.CharField(max_length=255)),
                ('odometro_inicio', models.IntegerField()),
                ('odometro_fim', models.IntegerField()),
                ('ts_inicio', models.DateTimeField()),
                ('ts_fim', models.DateTimeField()),
                ('gps_path', models.CharField(blank=True, max_length=255, null=True)),
                ('custos_fixos', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custos_variaveis', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
